[wip] テキストフィールドの作成
Jun-T-git/HackU.client pull request #5
Opened 2022-06-14 16:21 UTC by s-taku3

テキストフィールドの作成を行いました。
fieldフォルダにコンポーネントを追加する必要があると考えたため、feature/create-select-componentからブランチを切らせていただきました。
CSS修正の必要があるため、wipとしています。
next-env.d.tsの変更理由に関しては意図的なものではないたあめ調査中です。
![テキストフィールド](https://user-images.githubusercontent.com/66112754/173626760-0d32cc12-e56c-4c51-b5c8-257d4d0b3960.JPG)

2022-06-15 00:52 UTC, Jun-T-git requested changes
ほぼ想定通りの実装です！
細かいところになっちゃいますが，以下の箇所だけ修正してpushお願いします！

2022-06-15 00:52 UTC, Jun-T-git commented on src/components/field/textField.tsx
> +      />
以下2点修正お願いします！
- idにlabelのhtmlForと同じものを指定するようにしてください（[https://zenn.dev/kimura141899/articles/6e11e3a165460d](https://zenn.dev/kimura141899/articles/6e11e3a165460d)）
- placeholderは{...props}に含まれているのでなしで大丈夫です

2022-06-15 16:01 UTC, s-taku3 commented
該当箇所の修正を行いました。
idの追加とplaceholderの削除
placeholderを削除したことで、入力欄の文字が表示されなくなりましたが、問題ないでしょうか？

2022-06-16 01:32 UTC, Jun-T-git commented
@s-taku3 

> 該当箇所の修正を行いました。 idの追加とplaceholderの削除 placeholderを削除したことで、入力欄の文字が表示されなくなりましたが、問題ないでしょうか？

このように呼び出す側で指定すれば使えるので大丈夫です！
```
<TextField
          fieldId="email"
          label="メールアドレス"
          placeholder="test@example.com"
/>
```
![image](https://user-images.githubusercontent.com/64676197/173972322-bbed834e-a9d2-44eb-9cc2-096a5af6053d.png)

2022-06-16 01:32 UTC, Jun-T-git approved these changes
問題なさそうなのでマージします！

2022-06-16 01:33 UTC, merged